name: CodeQL Analysis

on:
  workflow_dispatch:

jobs:
  codeql:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # Adjust as needed

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Build with Maven
        run: mvn clean compile
        working-directory: JavaSampleApp  # 👈 change this to your actual folder

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
