name: CodeQL Analysis

on:
  workflow_dispatch:  # You can change this to `push`, `pull_request`, etc.

jobs:
  codeql:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # Update based on your project’s Java version

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Build with Maven
        run: mvn clean compile

      # Optional: Run tests to generate test coverage
      # - name: Run tests
      #   run: mvn test

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
