name: CodeQL Analysis

on:
  workflow_dispatch:

jobs:
  codeql:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java
          # Use the main security-and-quality pack plus the secret scanning community pack
          
          queries: security-extended
          
        

      - name: Compile Java manually
        run: javac Demo.java  # 👈 compile the standalone file

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
